// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqga8nZhS7zpmnY_noodKzKwMg8ehNrs8',
    appId: '1:816493398738:web:b8975f38f14a1b19bcfb0b',
    messagingSenderId: '816493398738',
    projectId: 'ess-back',
    authDomain: 'ess-back.firebaseapp.com',
    databaseURL: 'https://ess-back-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ess-back.appspot.com',
    measurementId: 'G-KRNWKKZDPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBFsWVYyCUeuRs0VjgjFwG4vpwpvv4K2Q',
    appId: '1:816493398738:android:6d123b296be4d9cfbcfb0b',
    messagingSenderId: '816493398738',
    projectId: 'ess-back',
    databaseURL: 'https://ess-back-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ess-back.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkxF3eTUO5TebeBHvldbCpnYbTQ3K6SV4',
    appId: '1:816493398738:ios:4b4796da71d2cb92bcfb0b',
    messagingSenderId: '816493398738',
    projectId: 'ess-back',
    databaseURL: 'https://ess-back-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ess-back.appspot.com',
    iosClientId: '816493398738-kvg8u0ttn6mvr01khtk3gd6jc9inj5dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.essApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkxF3eTUO5TebeBHvldbCpnYbTQ3K6SV4',
    appId: '1:816493398738:ios:4b4796da71d2cb92bcfb0b',
    messagingSenderId: '816493398738',
    projectId: 'ess-back',
    databaseURL: 'https://ess-back-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ess-back.appspot.com',
    iosClientId: '816493398738-kvg8u0ttn6mvr01khtk3gd6jc9inj5dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.essApp',
  );
}
